### ISSUE TITLE
Do not update changelog file during a dry run.

### ISSUE THREAD

**Issue by rwjblue** [release-it/conventional-changelog#1]
Based on the logic here:

https://github.com/release-it/conventional-changelog/blob/6b84de1bf3d495d8f4551c74351ad1055d220039/index.js#L58-L65

When `infile` is specified, the file is always updated regardless of the status of `this.global.isDryRun`.

**Comment by rwjblue** [comment]
FWIW, I implemented the dry run detection here:

https://github.com/rwjblue/release-it-lerna-changelog/blob/a7ed4a6101e622d5b71156c92b5af647e94e98a6/index.js#L73-L78

**Comment by webpro** [comment]
Thanks, @rwjblue! Should be fixed in [v1.0.1](https://github.com/release-it/conventional-changelog/releases/tag/1.0.1)
