### ISSUE TITLE
Should not include release-it as dependency

### ISSUE THREAD

**Issue by rchl** [release-it/conventional-changelog#10]
This package includes `release-it` as a dependency:
https://github.com/release-it/conventional-changelog/blob/37c6683651df6178ba22606c36b7b3a293043364/package.json#L37

I believe it shouldn't do that and instead have it in `devDependencies`.

The reasoning is that this is a plugin for `release-it` so `release-it` must be installed separately anyway and this makes it so that there are two different versions of `release-it` included in the project.

**Comment by rchl** [comment]
@webpro Would you say this is a valid issue?

**Comment by webpro** [comment]
Maybe... looking at https://docs.npmjs.com/files/package.json#peerdependencies:

> In some cases, you want to express the compatibility of your package with a host tool or library, while not necessarily doing a require of this host. This is usually referred to as a plugin. Notably, your module may be exposing a specific interface, expected and specified by the host documentation.

This plugin does a direct `require('release-it')`. So I think it's the recommended way to have it as a regular dependency. I totally agree there should not be two versions of release-it installed, so I'm happy to be convinced otherwise. Maybe there are examples that successfully use `peerDependencies` (or any other solution)?

**Comment by rchl** [comment]
`peerDependencies` is a perfect solution for this case since this plugin requires `release-it` to work but doesn't want to decide the specific version of it (within a given major range at least).

That's one of the use cases of `peerDependencies`, I'd say.

One popular example of similar setup is `type-graphql` where it requires a `graphql` dependency to work properly but doesn't depend on it itself as that would create multiple versions of `graphql` library and potential conflicts.
https://github.com/MichalLytek/type-graphql/blob/master/package.json

**Comment by webpro** [comment]
Alright, you've convinced me, thank you. I'm working on a major update for release-it (v14) with a breaking change for plugins, so it's a good moment to include this change as well. Leaving this ticket open until it's done.

**Comment by webpro** [comment]
The plugins have been updated to use release-it (v14) as a peer dependency. Thanks again for your ideas, @rchl!
