### ISSUE TITLE
Feature: default `header` to `"# Changelog"`

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [release-it/conventional-changelog#108]
https://github.com/release-it/conventional-changelog?tab=readme-ov-file#header mentions `"header": "# Changelog"` as a suggested option. Which strikes me as pretty reasonable.

Files should start with a generally high-level heading and increase the level no more than one at a time. Having a `#` h1 at the start is a pretty common setting.

Is there any reason not to default `header` to `"# Changelog"`?

If it helps, I'm coming over from https://github.com/JoshuaKGoldberg/create-typescript-app/issues/915, working on setting up headings in packages based on https://www.w3.org/WAI/tutorials/page-structure/headings.

**Comment by webpro** [comment]
Agreed! It's in v9.0.4 🚀
