### ISSUE TITLE
Only last commit made has effect on verison bump and written to changelog

### ISSUE THREAD

**Issue by b12k** [release-it/conventional-changelog#16]
Hello.
In my `release-it` + `@release-it/conventional-changelog` setup only last commit made is affecting version bump and written to the changelog.
Also only last commit is taken in to consideration when bumping a version.
So if:
- v0.1.0
- commit `feat`
- commit `fix` _<= this one used_
- v0.1.1 (not v0.2.0)

Example repo: https://github.com/b12k/gh-action-release-it

This repo uses github action to do an automated release on PR merge to master (using rebase).

I would appreciate some advice on why it may happen.

Thanx in advance.

UPDATE:

<details>
  <summary>Here is git log</summary>

      commit af26c4a5effc9caa01d6110741e991e83bdeb0f5 (HEAD -> master, origin/master)
      Author: ci <ci@b12k.com>
      Date:   Wed Feb 10 12:33:08 2021 +0000
      
          ci: release 0.1.2
      
      commit 9fc3e73f36beca6dc351e9bee40cb6f6792e96a7
      Author: Bogdan Kolesnyk <bogdan.kolesnyk@gmail.com>
      Date:   Wed Feb 10 13:31:56 2021 +0100
      
          fix: dummy fix commit
      
      commit 6714424d45175ef420f39e82f88e611489a61fbc
      Author: Bogdan Kolesnyk <bogdan.kolesnyk@gmail.com>
      Date:   Wed Feb 10 13:31:35 2021 +0100
      
          feat: enable debug mode
      
      commit f07d4f5984f1d3388f6fff687bd1a86beb2878f1
      Author: ci <ci@b12k.com>
      Date:   Wed Feb 10 12:19:26 2021 +0000
      
          ci: release 0.1.1
      
      commit 560aa843694f8ec3e23c9194a55203c69e8c55cf
      Author: Bogdan Kolesnyk <bogdan.kolesnyk@gmail.com>
      Date:   Wed Feb 10 13:18:23 2021 +0100
      
          fix: fix 1
      
      commit daddac8be0da536e1b1ce4ccd170392fb76cf3cf
      Author: Bogdan Kolesnyk <bogdan.kolesnyk@gmail.com>
      Date:   Wed Feb 10 13:17:55 2021 +0100
      
          feat: feat 2
      
      commit 48a71f8e81c23ba3efce6fe39cf07a2801221a82
      Author: ci <ci@b12k.com>
      Date:   Wed Feb 10 11:32:27 2021 +0000
      
          ci: release 0.1.0
      
      commit 39f3e39a71b456e206674bc1ad2b17682ec42fef
      Author: Bogdan Kolesnyk <bogdan.kolesnyk@gmail.com>
      Date:   Wed Feb 10 12:31:24 2021 +0100
      
          feat: feat 1
      
      commit df1d2d0457145a4ca79832259c51d4ca6026332c
      Author: Bogdan Kolesnyk <bogdan.kolesnyk@gmail.com>
      Date:   Wed Feb 10 12:29:55 2021 +0100
      
          initial

</details>

<details>
  <summary>Debug</summary>

      > release-it-exp@0.1.1 release /home/runner/work/gh-action-release-it/gh-action-release-it
      > DEBUG=release-it:* release-it --git.requireBranch=master
      
      2021-02-10T12:33:07.678Z release-it:config {
        cosmiconfig: {
          config: {
            plugins: [Object],
            git: [Object],
            npm: [Object],
            github: [Object]
          },
          filepath: '/home/runner/work/gh-action-release-it/gh-action-release-it/package.json'
        }
      }
      2021-02-10T12:33:07.682Z release-it:config {
        system: { 'release-it': '14.3.0', node: 'v12.20.1', os: 'Linux 5.4' }
      }
      2021-02-10T12:33:07.682Z release-it:config {
        _: [],
        git: {
          requireBranch: 'master',
          push: true,
          commitMessage: 'ci: release ${version}',
          pushArgs: [ '--follow-tags' ],
          changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
          requireCleanWorkingDir: true,
          requireUpstream: true,
          requireCommits: false,
          addUntrackedFiles: false,
          commit: true,
          commitArgs: [],
          tag: true,
          tagName: null,
          tagAnnotation: 'Release ${version}',
          tagArgs: [],
          pushRepo: ''
        },
        increment: undefined,
        ci: true,
        plugins: {
          '@release-it/conventional-changelog': { infile: 'CHANGELOG.md', preset: [Object] }
        },
        npm: {
          publish: false,
          publishPath: '.',
          tag: null,
          otp: null,
          ignoreVersion: false,
          skipChecks: false,
          timeout: 10
        },
        github: {
          release: true,
          releaseName: 'Release ${version}',
          releaseNotes: null,
          preRelease: false,
          draft: false,
          tokenRef: 'GITHUB_TOKEN',
          assets: null,
          host: null,
          timeout: 0,
          proxy: null,
          skipChecks: false
        },
        hooks: {},
        gitlab: {
          release: false,
          releaseName: 'Release ${version}',
          releaseNotes: null,
          tokenRef: 'GITLAB_TOKEN',
          assets: null,
          origin: null,
          skipChecks: false
        },
        isUpdate: false,
        version: {
          increment: undefined,
          isPreRelease: false,
          preReleaseId: undefined
        }
      }
      2021-02-10T12:33:07.846Z release-it:config {
        'conventional-changelog': {
          infile: 'CHANGELOG.md',
          preset: { name: 'angular', types: [Array] }
        }
      }
      2021-02-10T12:33:07.847Z release-it:plugins {
        namespace: 'conventional-changelog',
        options: {
          infile: 'CHANGELOG.md',
          preset: { name: 'angular', types: [Array] },
          tagName: null
        }
      }
      2021-02-10T12:33:07.857Z release-it:plugins {
        namespace: 'npm',
        options: {
          publish: false,
          publishPath: '.',
          tag: null,
          otp: null,
          ignoreVersion: false,
          skipChecks: false,
          timeout: 10
        }
      }
      2021-02-10T12:33:07.859Z release-it:plugins {
        namespace: 'github',
        options: {
          release: true,
          releaseName: 'Release ${version}',
          releaseNotes: null,
          preRelease: false,
          draft: false,
          tokenRef: 'GITHUB_TOKEN',
          assets: null,
          host: null,
          timeout: 0,
          proxy: null,
          skipChecks: false,
          tagName: null,
          pushRepo: '',
          changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
          isUpdate: false
        }
      }
      2021-02-10T12:33:07.863Z release-it:plugins {
        namespace: 'git',
        options: {
          requireBranch: 'master',
          push: true,
          commitMessage: 'ci: release ${version}',
          pushArgs: [ '--follow-tags' ],
          changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
          requireCleanWorkingDir: true,
          requireUpstream: true,
          requireCommits: false,
          addUntrackedFiles: false,
          commit: true,
          commitArgs: [],
          tag: true,
        repo: 'gh-action-release-it',
        tag_name: '0.1.2',
        name: 'Release 0.1.2',
        body: '## 0.1.2 (2021-02-10)\n' +
          '\n' +
          '\n' +
          '### Bug Fixes\n' +
          '\n' +
          '* dummy fix commit ([9fc3e73](https://github.com/b12k/gh-action-release-it/commit/9fc3e73f36beca6dc351e9bee40cb6f6792e96a7))',
        draft: false,
        prerelease: false
      }
      POST /repos/b12k/gh-action-release-it/releases - 201 in 407ms
      2021-02-10T12:33:12.044Z release-it:github {
        url: 'https://api.github.com/repos/b12k/gh-action-release-it/releases/37858104',
        assets_url: 'https://api.github.com/repos/b12k/gh-action-release-it/releases/37858104/assets',
        upload_url: 'https://uploads.github.com/repos/b12k/gh-action-release-it/releases/37858104/assets{?name,label}',
        html_url: 'https://github.com/b12k/gh-action-release-it/releases/tag/0.1.2',
        id: 37858104,
        author: {
          login: 'b12k',
          id: 10243265,
          node_id: 'MDQ6VXNlcjEwMjQzMjY1',
          avatar_url: 'https://avatars.githubusercontent.com/u/10243265?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/b12k',
          html_url: 'https://github.com/b12k',
          followers_url: 'https://api.github.com/users/b12k/followers',
          following_url: 'https://api.github.com/users/b12k/following{/other_user}',
          gists_url: 'https://api.github.com/users/b12k/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/b12k/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/b12k/subscriptions',
          organizations_url: 'https://api.github.com/users/b12k/orgs',
          repos_url: 'https://api.github.com/users/b12k/repos',
          events_url: 'https://api.github.com/users/b12k/events{/privacy}',
          received_events_url: 'https://api.github.com/users/b12k/received_events',
          type: 'User',
          site_admin: false
        },
        node_id: 'MDc6UmVsZWFzZTM3ODU4MTA0',
        tag_name: '0.1.2',
        target_commitish: 'master',
        name: 'Release 0.1.2',
        draft: false,
        prerelease: false,
        created_at: '2021-02-10T12:33:08Z',
        published_at: '2021-02-10T12:33:11Z',
        assets: [],
        tarball_url: 'https://api.github.com/repos/b12k/gh-action-release-it/tarball/0.1.2',
        zipball_url: 'https://api.github.com/repos/b12k/gh-action-release-it/zipball/0.1.2',
        body: '## 0.1.2 (2021-02-10)\n' +
          '\n' +
          '\n' +
          '### Bug Fixes\n' +
          '\n' +
          '* dummy fix commit ([9fc3e73](https://github.com/b12k/gh-action-release-it/commit/9fc3e73f36beca6dc351e9bee40cb6f6792e96a7))'
      }
      🔗 https://github.com/b12k/gh-action-release-it/releases/tag/0.1.2
      2021-02-10T12:33:12.090Z release-it:metrics {
      🏁 Done (in 4s.)
        url: 'http://www.google-analytics.com/collect',
        statusCode: 200,
        statusMessage: 'OK',
        payload: 't=event&ec=session&ea=end'
      }

</details>

**Comment by webpro** [comment]
Not sure about the issue here. The `options` for the plugin are passed verbatim to the [conventional-recommended-bump](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump) function.

I have just updated the dependencies and added more debug output in v2.0.1 of this plugin. However, I'm surprised not to see debug output from this plugin at all in your output. Can you please update release-it and this plugin, and run this to see what's going on, in what order:

```
DEBUG_DEPTH=null DEBUG=release-it:* release-it [...]
```

In your example repo I get this (after going back one commit), which seems correct:

```
release-it:conventional-changelog {
  release-it:conventional-changelog   increment: undefined,
  release-it:conventional-changelog   latestVersion: '0.1.1',
  release-it:conventional-changelog   isPreRelease: false,
  release-it:conventional-changelog   preReleaseId: undefined
  release-it:conventional-changelog } +0ms
  release-it:conventional-changelog conventionalRecommendedBump {
  options: {
    infile: 'CHANGELOG.md',
    preset: { name: 'angular', types: [Array] },
    tagName: null
  }
} +0ms
  release-it:conventional-changelog {
  release-it:conventional-changelog   err: null,
  release-it:conventional-changelog   result: {
  release-it:conventional-changelog     level: 1,
  release-it:conventional-changelog     reason: 'There are 0 BREAKING CHANGES and 1 features',
  release-it:conventional-changelog     releaseType: 'minor'
  release-it:conventional-changelog   }
  release-it:conventional-changelog } +50ms
  release-it:conventional-changelog conventionalChangelog {
  options: {
    infile: 'CHANGELOG.md',
    preset: { name: 'angular', types: [Array] },
    tagName: null
  },
  context: { version: '0.2.0', previousTag: '0.1.1', currentTag: '0.2.0' },
  gitRawCommitsOpts: {
    debug: [Function: debug] {
      namespace: 'release-it:conventional-changelog',
      useColors: true,
      color: 32,
      extend: [Function: extend],
      destroy: [Function: deprecated],
      enabled: [Getter/Setter],
      inspectOpts: [Object],
      diff: 1,
      prev: 1614029374251,
      curr: 1614029374252
    }
  }
} +1ms
  release-it:conventional-changelog Your git-log command is:
  release-it:conventional-changelog git log --format=%B%n-hash-%n%H%n-gitTags-%nNaN%n-committerDate-%n%ci%n------------------------ >8 ------------------------ 0.1.1 --no-merges
  release-it:conventional-changelog Your git-log command is:
  release-it:conventional-changelog git log --format=%B%n-hash-%n%H%n-gitTags-%nNaN%n-committerDate-%n%ci%n------------------------ >8 ------------------------ 0.1.1..HEAD --no-merges
  release-it:config {
  release-it:config   name: 'release-it-exp',
  release-it:config   latestVersion: '0.1.1',
  release-it:config   version: undefined,
  release-it:config   changelog: '# [0.2.0](https://github.com/b12k/gh-action-release-it/compare/0.1.1...0.2.0) (2021-02-22)\n' +
  release-it:config     '\n' +
  release-it:config     '\n' +
  release-it:config     '### Bug Fixes\n' +
  release-it:config     '\n' +
  release-it:config     '* dummy fix commit ([9fc3e73](https://github.com/b12k/gh-action-release-it/commit/9fc3e73f36beca6dc351e9bee40cb6f6792e96a7))\n' +
  release-it:config     '\n' +
  release-it:config     '\n' +
  release-it:config     '### Features\n' +
  release-it:config     '\n' +
  release-it:config     '* enable debug mode ([6714424](https://github.com/b12k/gh-action-release-it/commit/6714424d45175ef420f39e82f88e611489a61fbc))'
  release-it:config } +268ms
```

**Comment by b12k** [comment]
I did an update of the repo

**Comment by b12k** [comment]
I found a problem.
It's not in `release-it` or its plugins.

When creating CI with Github Actions using `actions/checkout@v2` do not forget to explicitly set `fetch-depth: 0`. It is `1` by default. So it means that ONLY last commit made will be fetched.

```
[...]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 <= THIS HELPS =)
[...]
```

Thank you @webpro for an awesome tool!

**Comment by webpro** [comment]
Thanks @b12k! Glad you figured it out. I've added a comment to the docs on both this plugin and release-it itself.

**Comment by fbonander** [comment]
@b12k Thanks, wouldn't have found that in a million years.
