### ISSUE TITLE
Possible to use @release-it/conventional-changelog for only CHANGELOG generation and not automatic version bump?

### ISSUE THREAD

**Issue by brandondurham** [release-it/conventional-changelog#17]
I have the `@release-it/conventional-changelog` plugin added which of course handles the version bump automatically as well as CHANGELOG generation. I would still like to select the version manually, as you can without this plugin, but I’m unsure if there is a way to disable that particular step.

```json
"plugins": {
  "@release-it/conventional-changelog": {
    "preset": "angular",
    "infile": "CHANGELOG.md"
  }
},
```

Is it possible to disable/skip the `conventional-recommended-bump` step?

**Comment by navono** [comment]
@brandondurham 
I have the same requirement, Do you have any solution now?

**Comment by webpro** [comment]
Yes, please upgrade to v3 (depends on release-it v14.8) and set `ignoreRecommendedBump: true`
