### ISSUE TITLE
Allow to override bump

### ISSUE THREAD

**Issue by LeBenLeBen** [release-it/conventional-changelog#2]
Since release-it 12, version number or bump given manually, like `release-it patch` or `release-it 1.0.0` is ignored when using conventional changelog.

As said in https://github.com/release-it/release-it/issues/526 this is a feature that can be useful sometimes when for some reasons you want to bypass the auto bump and release a specific version.

I'd love to see that feature back 🙇

**Comment by webpro** [comment]
It's back in [v1.1.0](https://github.com/release-it/conventional-changelog/releases/tag/1.1.0) (w/ release-it v12.2.1)
