### ISSUE TITLE
Unacceptable kind of an object to dump [object Undefined]

### ISSUE THREAD

**Issue by ivandov** [release-it/conventional-changelog#23]
When attempting to use the `conventional-changelog` plugin in a newly created repo with no existing versions in `git tags`, `conventional-changelog` fails to properly set an initial version of `0.0.1` that should be provided by the `release-it` core `bump` module.

```
🚀 Let's release cics (currently at null)

Changelog:
##  (2021-06-28)

### Features
* foo
* bar

### Fixes
* foo

### Doc Updates
* foo

### CI Changes
* foo
* bar

ERROR unacceptable kind of an object to dump [object Undefined]
```

To get around this error, an initial version **must** be pushed with `release-it -i`. Then all following `conventional-changelog` versioning works as expected.

**Comment by webpro** [comment]
I agree release-it or this plugin should provide a solution here.

**Comment by webpro** [comment]
There's a solution in release-it core, so I'm going to close this issue.
