### ISSUE TITLE
Cannot read property 'ignoreRecommendedBump' of undefined

### ISSUE THREAD

**Issue by ajaykumar97** [release-it/conventional-changelog#24]
I am trying to use this plugin with `release-it` to auto-generate the change-logs but when I tried to run the `release-it patch` script, I am getting:

```bash
> release-it "patch"

ERROR Cannot read property 'ignoreRecommendedBump' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <package_name>@0.1.7 release: `release-it "patch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the <package_name>@0.1.7 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

`.release-it.json` file content:

```json
{
  "git": {
    "commitMessage": "chore: release v${version}"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }    
}
```

Dependencies versions:
"@release-it/conventional-changelog": "^3.0.1",
"release-it": "^14.6.2"

**Comment by webpro** [comment]
There should have been some error or warning from npm, as you need at least release-it v14.8.0 with that version of the conventional-changelog plugin.

**Comment by ajaykumar97** [comment]
It worked after I reinstalling the `release-it` with version `14.10.0`. Thanks 👍🏼 .
It will be more helpful if the supported `release-it` version with the respective `conventional-changelog` version is listed in the main Readme file 🙂 .
