### ISSUE TITLE
'Cannot read property 'replace' of undefined'

### ISSUE THREAD

**Issue by TheRealWaldo** [release-it/conventional-changelog#26]
Get 'Cannot read property 'replace' of undefined' when run programmatically.  Setting with 'git: false'.

A little back-searching, it seems to be tagTemplate that is undefined in getChangelogStream.

Rolling back to 3.0.1 works.

**Comment by webpro** [comment]
Thanks @TheRealWaldo. Should be fixed it in v3.1.1. Although, if I may ask, I wonder in which scenario you would use this plugin with `git: false`?

**Comment by TheRealWaldo** [comment]
Primarily for CI/CD automation;

The release-it git plugin fails on a pull request workflow (always thinks there is zero commits and dies with a fatal on a git command), but we need to run it to verify the GitHub action (and release-it) will still work.

The second case is that we have a two step release process, first we bump the version, sometimes rebuild (depending on the project) then we test that the bump worked and didn't break anything. If it worked we merge the bump, and then officially release.  With the git plugin enabled in conjunction with the bumper plugin, this results in two bumps (and some strange behavior with a different version in the changelog vs. The release vs. the files)  So we disable the git plugin in the second step, and use the file based bumper to read the version.

**Comment by TheRealWaldo** [comment]
@webpro latest update fails security scan; looks like a bad .replace

---------

Sanitizing untrusted input is a common technique for preventing injection attacks such as SQL injection or cross-site scripting. Usually, this is done by escaping meta-characters such as quotes in a domain-specific way so that they are treated as normal characters.

However, directly using the string replace method to perform escaping is notoriously error-prone. Common mistakes include only replacing the first occurrence of a meta-character, or backslash-escaping various meta-characters but not the backslash itself.

In the former case, later meta-characters are left undisturbed and can be used to subvert the sanitization. In the latter case, preceding a meta-character with a backslash leads to the backslash being escaped, but the meta-character appearing un-escaped, which again makes the sanitization ineffective.

Even if the escaped string is not used in a security-critical context, incomplete escaping may still have undesirable effects, such as badly rendered or confusing output.

Recommendation
Use a (well-tested) sanitization library if at all possible. These libraries are much more likely to handle corner cases correctly than a custom implementation.

An even safer alternative is to design the application so that sanitization is not needed, for instance by using prepared statements for SQL queries.

Otherwise, make sure to use a regular expression with the g flag to ensure that all occurrences are replaced, and remember to escape backslashes if applicable.

Note, however, that this is generally not sufficient for replacing multi-character strings: the String.prototype.replace method only performs one pass over the input string, and will not replace further instances of the string that result from earlier replacements.

For example, consider the code snippet s.replace(/\/\.\.\//g, ""), which attempts to strip out all occurences of /../ from s. This will not work as expected: for the string /./.././, for example, it will remove the single occurrence of /../ in the middle, but the remainder of the string then becomes /../, which is another instance of the substring we were trying to remove.

Example
For example, assume that we want to embed a user-controlled string accountNumber into a SQL query as part of a string literal. To avoid SQL injection, we need to ensure that the string does not contain un-escaped single-quote characters. The following function attempts to ensure this by doubling single quotes, and thereby escaping them:

function escapeQuotes(s) {
  return s.replace("'", "''");
}
As written, this sanitizer is ineffective: if the first argument to replace is a string literal (as in this case), only the first occurrence of that string is replaced.

As mentioned above, the function escapeQuotes should be replaced with a purpose-built sanitization library, such as the npm module sqlstring. Many other sanitization libraries are available from npm and other sources.

If this is not an option, escapeQuotes should be rewritten to use a regular expression with the g ("global") flag instead:

function escapeQuotes(s) {
  return s.replace(/'/g, "''");
}
Note that it is very important to include the global flag: s.replace(/'/, "''") without the global flag is equivalent to the first example above and only replaces the first quote.

References
OWASP Top 10: A1 Injection.
npm: sqlstring package.
Common Weakness Enumeration: CWE-116.
Common Weakness Enumeration: CWE-20.

**Comment by TheRealWaldo** [comment]
@webpro that security issue might be an upstream change; aside from some redundant escaping, I can't see an obvious problem in the recent changes.

**Comment by TheRealWaldo** [comment]
@webpro  strange behavior now, that didn't exist before:

- The changelog includes the previous version
- The GitHub release plugin updates the previous release with the current release notes, and the new release version, and does not create a new release, effectively destroying release history

-------
  Using --no-increment with --github.release is deprecated. Add --github.update in release-it v15.
  🚀 Let's update release-it (currently at 0.6.1)
  Changelog:
  ### [0.6.1](https://github.com/TheRealWaldo/release-it/compare/v0.5.3...v0.6.0) (2021-08-13)
  ## [0.6.0](https://github.com/TheRealWaldo/release-it/compare/v0.5.3...v0.6.0) (2021-08-07)
  
  ### Features
  * fail if required inputs are not set ([a003cf1](https://github.com/TheRealWaldo/release-it/commit/a003cf131e0393d1fac0e4cf77e05b4a7fb90ca1))
  
  ### Bug Fixes
  * imports ([7c25850](https://github.com/TheRealWaldo/release-it/commit/7c2585064bab1c96ffe6ba57675bb16e16dd4fb9))
  * properly handle error ([42e50d4](https://github.com/TheRealWaldo/release-it/commit/42e50d4bfb4eb03f24f00a3da2a5a8a36ff57304))
  * remote branch not detected ([94e47bb](https://github.com/TheRealWaldo/release-it/commit/94e47bb9a214a3acb2dd5733a01ebb417999fd9e))
  * remote branch not detected ([9de163d](https://github.com/TheRealWaldo/release-it/commit/9de163da95d835e9890b2cf0c8af5cd296e3eee8))
  * set property requiredUpstream of undefined ([7f18842](https://github.com/TheRealWaldo/release-it/commit/7f1884247923b3d2a7964b5d0562e3e3de0a149a))
  * unhandled promise rejection ([45812c9](https://github.com/TheRealWaldo/release-it/commit/45812c91738a9397154bc46a251d798768e0e907))

**Comment by webpro** [comment]
As I think the original issue is fixed, I'm going to close this issue.
