### ISSUE TITLE
`gitRawCommitsOpts` support

### ISSUE THREAD

**Issue by LastDragon-ru** [release-it/conventional-changelog#29]
By default `conventional-changelog` doesn't include merge commits, this can be fixed via `gitRawCommitsOpts: {merges: true}` (tested on the latest version), unfortunately, there is no way to set this option.

![image](https://user-images.githubusercontent.com/1329824/129473697-c69bce76-8cd6-4afa-9bd0-86742906f053.png)

**Comment by webpro** [comment]
It is now in [v3.2.0](https://github.com/release-it/conventional-changelog/releases/tag/3.2.0) :)

**Comment by LastDragon-ru** [comment]
How fast 😁 Thank you!

![image](https://user-images.githubusercontent.com/1329824/129475909-aae83c24-cfcf-4e79-a67b-d68e2d4ffe58.png)
