### ISSUE TITLE
How to run a command after the changelog is generated?

### ISSUE THREAD

**Issue by LeBenLeBen** [release-it/conventional-changelog#3]
I recently upgraded from version 10 and I got an issue with the order in which things are done. Here’s my config:

```json
{
  "scripts": {
    "afterRelease": "npm run deploy",
    "afterBump": "npm run build"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```

In previous release-it versions, the bump and the changelog used to be done before my `npm run build` command was run. It was perfect for me as I use the changelog in this command. Now the changelog gets written after the build, which cause the changelog of the previous version to be used.

I tried to change the `afterBump` to `beforeStage` or `beforeRelease` like it is in the conventional-changelog plugin but the changelog still gets written after.

I think there was a `safeBump` option previously to avoid that but I saw it got deprecated and removed from the docs. What would be the new way of running a command _after_ the changelog is written but _before_ stage?

(Sorry if this is more a question for the main repository)

For reference, here’s how I used to do it with previous versions:

```json
{
  "increment": "conventional:angular",
  "scripts": {
    "changelog": "conventional-changelog -p angular | tail -n +3",
    "beforeStage": "conventional-changelog -p angular -i CHANGELOG.md -s",
    "afterRelease": "npm run deploy",
    "afterBump": "npm run build"
  }
}
```

**Comment by webpro** [comment]
> It was perfect for me as I use the changelog in this command.

Unfortunately release-it v11 doesn't turn out well for your use case. You can still use `scripts.beforeStage` but indeed the changelog isn't generated available yet.

The solution would be to create a plugin to do something at that point (using the `plugin.release` method). This could be as simple as moving shell a script into `this.exec` commands, but obviously this depends on what "npm run build" should do. Happy to help out with this (but please file issues in the main repo if appropriate).

**Comment by webpro** [comment]
@LeBenLeBen As I was working on https://github.com/release-it/release-it/pull/529, this might be a solution for your use case as well. Please see the other issue.

Not sure exactly what you need, but something like `hooks["before:git:release"]` (or `hooks["after:conventional-changelog:beforeRelease"]`) sounds about right to do the build.

What do you think? Could you please try `npm install release-it@next` and see if this works for you?

**Comment by LeBenLeBen** [comment]
Amazing, it works perfectly by hooking it after the conventional changelog task! 🙇

**Comment by webpro** [comment]
Great! Thanks for your feedback. I'll be releasing v12.3.0 soon :)
