### ISSUE TITLE
Inform parseOpts and writerOpts

### ISSUE THREAD

**Issue by rondymesquita** [release-it/conventional-changelog#31]
Hi, this is not an issue itself. It is more like a question.

How can I inform both parseOpts and writerOpts.
I see that conventional-changelog-core have an API like `conventionalChangelogCore([options, [context, [gitRawCommitsOpts, [parserOpts, [writerOpts]]]]])`, and I would like to pass some parameters to writerOpts like:
```js
writerOpts: {
  groupBy: 'scope'
}
```
so I can group commits by scope instead of type by default.

Thank in advance.

**Comment by webpro** [comment]
That's currently not possible. It's a bit of a coincidence I guess, but if you look at the last 5 commits of this repo, you'll find `context` and `gitRawCommitsOpts` were just added. So feel free to add the options you need in the same way in a PR and I'll be happy to merge.

**Comment by rondymesquita** [comment]
Oh! Good to know! I will prepare the code and push it soon! Thanks for the feedback!

**Comment by rondymesquita** [comment]
Hi @webpro , I have opened a PR for this change.
https://github.com/release-it/conventional-changelog/pull/32
