### ISSUE TITLE
ConventionalChangelog fails after release-it 14.11.5

### ISSUE THREAD

**Issue by lpreterite** [release-it/conventional-changelog#38]
ConventionalChangelog fails after release-it 14.11.5

Using @release-it/conventional-changelog under the latest version of release-it (14.11.7) found that the CHANGELOG record lost the version information, like this:

```
Changelog:
* build: update @release-it/conventional-changelog (a31d21f)
* build: Update all package versions (4087cbe)
```

Comparing the two versions, it is found that the plug-in cannot get the version number.

It is shown in [release-it/lib/tasks.js](https://github.com/release-it/release-it/compare/14.11.5...14.11.7#diff-80b0520dd0dbcf7162aba6a748e053a5ab7d2f96603a96e60fc710249f535dbf) and [release- it/conventional-changelog/index.js](https://github.com/release-it/conventional-changelog/blob/master/index.js#L21)

**Comment by webpro** [comment]
Thanks @lpreterite! Reverted this change right away in release-it v14.11.8
