### ISSUE TITLE
Duplicated `# Changelog` header in the updated `infile`

### ISSUE THREAD

**Issue by beata** [release-it/conventional-changelog#39]
relase-it config
```
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  },
```

The generated `infile`(e.g. Changelog.md) would have multiple `# Changelog` headers like this:
```
# Changelog

## v1.2.3 (2021-11-21)
...

# Changelog

## v1.2.2 (2021-11-16)
...
```

Generally, we want only one `h1` in a document but this behavior cannot be achieved through configuration because `writeChangelog()` would always prepend new changelog to the `infile`:
```
async writeChangelog() {
    ...
    let { changelog } = this.config.getContext();
    ...
    await prependFile(infile, changelog + EOL + EOL);
```

When`infile` already has `# Changelog` and changelog has another `# Changelog`. We'll get several `# Changelog` header after several version bumps.

I also figure out that there's a relational rejected PR #18 resolves this problem.

**Comment by webpro** [comment]
This should be fixed by now indeed.
