### ISSUE TITLE
Semver is not declared in dependencies

### ISSUE THREAD

**Issue by cravend** [release-it/conventional-changelog#49]
Hi y'all!

I'm trying to use this with Yarn berry, but I'm running into an issue:

```bash
ERROR @release-it/conventional-changelog tried to access semver, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: semver (via "semver/package.json")
Required by: @release-it/conventional-changelog@virtual:f8628a01fc8a0c88efe1afe17f2bd962a545e2644e7bc646f13ee6114785601dea0fc25e5105597cdbff6bdbc249a1f8dc91aaafa859915fd961e5dec7c0ab9f#npm:5.0.0 (via /Users/cravend/src/html/object-access/.yarn/__virtual__/@release-it-conventional-changelog-virtual-9949b6766b/0/cache/@release-it-conventional-changelog-npm-5.0.0-19f49b5e03-205a743018.zip/node_modules/@release-it/conventional-changelog/index.js)
```

Is there any reason semver shouldn't be included in the dependencies array?

**Comment by Jungho-Cheon** [comment]
same issue here.

are you using yarn berry with pnp?

**Comment by webpro** [comment]
Yarn Berry is not officially supported by release-it (it uses npm not Yarn to version and publish). Things may or may not work depending on local workflow and config etc.

Feel free to open a PR with improvements, though, happy to discuss and look into it.

**Comment by webpro** [comment]
Oh wait, sorry, yes `semver` should definitely be a `dependency`. Will fix this shortly!

**Comment by webpro** [comment]
This is in [v5.1.0](https://github.com/release-it/conventional-changelog/releases/tag/5.1.0)
