### ISSUE TITLE
npm install creates a big package.json and node_modules directory

### ISSUE THREAD

**Issue by hernanmd** [release-it/conventional-changelog#5]
My context is to use the conventional-changelog in a non-npm project (actually a bash project). Running the command to install the module creates a 127Kb package.json file, and a node_modules directory with 327 sub-directories. Is this expected? 

```
npm install --save-dev @release-it/conventional-changelog
npm WARN saveError ENOENT: no such file or directory, open '/Users/testuser/git_projects/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/testuser/git_projects/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
```

**Comment by webpro** [comment]
The `package.json` should only be small, e.g.:

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@release-it/conventional-changelog": "^1.1.0"
  }
}
```

The lockfile (`package-lock.json`) can be large indeed, like the number of directories in `node_modules`. All of this is handled by npm. The [dependencies of this project](https://github.com/release-it/conventional-changelog/blob/master/package.json) also have sub-dependencies, etc.

**Comment by hernanmd** [comment]
Thank you, for now I added a minimal package.json as you suggested, then kept the hook 

```
    "hooks": {
        "after:bump": "npx auto-changelog -p"
      },
```

and removed the plugin code

```
    "plugins": {
        "@release-it/conventional-changelog": {
          "preset": "cli",
          "infile": "CHANGELOG.md"
        }
```

In my release-it.json

I still need to understand the difference between

```
    "git": {
    ...
     "changelog": "npx auto-changelog --stdout --commit-limit false -u --template ./.changelog.hbs"
   }
```

and

```
   "hooks": {
        "after:bump": "npx auto-changelog -p"
      }
```

For a humble feedback I suggest to make clear in the docs for non-JS projects since not everybody work daily with JS and it could be not obvious what/where to add artifacts.

**Comment by webpro** [comment]
The `git.changelog` command should return the Git changelog and this will be used for two things:

* Show on the command-line the changelog to help selecting a next version
* Use it as release notes when doing a GitHub or GitLab release (unless e.g. `github.releaseNotes` is used to override this).

The hook command `auto-changelog -p` is executing [auto-changelog](https://www.npmjs.com/package/auto-changelog) to update the `CHANGELOG.md` file (which you could also do with the `@release-it/conventional-changelog` plugin by setting its `infile` option).

I've also updated the documentation a bit (https://github.com/release-it/release-it/blob/master/docs/github-releases.md#release-notes). Thanks!
