### ISSUE TITLE
The "hidden" property doesn't work

### ISSUE THREAD

**Issue by CT-AndrasSzabo** [release-it/conventional-changelog#50]
The `hidden` property doesn't work for me. If I have this release-it config:
```
{
  "git": {
    "commit": true,
    "commitMessage": "chore(release): v${version}",
    "commitArgs": "",
    "tag": true,
    "tagName": "v${version}",
    "tagAnnotation": "v${version}",
    "push": true,
    "requireCommits": true,
    "requireUpstream": false
  },
  "npm": {
    "publish": false
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md",
      "types": [
        { "type": "feat", "section": "Features", "hidden": false },
        { "type": "fix", "section": "Bug Fixes", "hidden": false },
        {
          "type": "perf",
          "section": "Performance Improvements",
          "hidden": false
        },
        { "type": "revert", "section": "Reverts", "hidden": false },
        { "type": "docs", "section": "Documentation", "hidden": false },
        { "type": "style", "section": "Styles", "hidden": false },
        { "type": "chore", "section": "Miscellaneous Chores", "hidden": false },
        { "type": "refactor", "section": "Code Refactoring", "hidden": false },
        { "type": "test", "section": "Tests", "hidden": false },
        { "type": "ci", "section": "Continuous Integration", "hidden": false }
      ]
    }
  }
}
```
...so I have `hidden: false` everywhere, despite of that only the `Features` and `Bug Fixes` section is visible in my CHANGELOG.md. It seems, that the `hidden` property doesn't have effect at all.
The command used to generating the changelog: `release-it --ci`. My release-it config file is called `.release-it.json`.

`release-it` version installed: `15.0.0`
`@release-it/conventional-changelog` version installed: `5.0.0`

**Comment by webpro** [comment]
This is probably an issue with [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog), the dependency that receives this configuration and parses the commits.

The docs of this plugin link you to their docs at https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

There I see that only `hidden: true` should affect the results.

**Comment by matatk** [comment]
AFAIK the angular preset is hard coded to only render feat and fix commits. Have you tried the conventionalvommits preset?

**Comment by webpro** [comment]
Closing this, nothing to be done here for this plugin.
