### ISSUE TITLE
npm audit issue

### ISSUE THREAD

**Issue by baronkoko** [release-it/conventional-changelog#51]
- "release-it": "^15.1.1";
- "@release-it/conventional-changelog": "^5.0.0";
- npm 8.3.1

Hi, I get this message after running the `npm audit fix` command
<img width="717" alt="Screenshot 2022-07-06 at 12 55 02" src="https://user-images.githubusercontent.com/27996386/177526340-3dcb36e1-d203-4d5c-9140-5a0a7f989780.png">
Can someone help please?

**Comment by rafaelmazzo** [comment]
Hi @baronkoko !
This issue is related for `release-it`, not `conventional-changelog`. 
There is an opened issue on it repository. You can check for updates there:

https://github.com/release-it/release-it/issues/917

All the best!
