### ISSUE TITLE
Build error in react-native projects

### ISSUE THREAD

**Issue by mlecoq** [release-it/conventional-changelog#52]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@release-it/conventional-changelog@5.0.0` for the project I'm working on.

On `react-native`, I have the following error while building my project 

Invalid `Podfile`  unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/expo/workingdir/build/node_modules/@release-it/conventional-changelog/package.json

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@release-it/conventional-changelog/package.json b/node_modules/@release-it/conventional-changelog/package.json
index 004a8b5..f37dc9b 100644
--- a/node_modules/@release-it/conventional-changelog/package.json
+++ b/node_modules/@release-it/conventional-changelog/package.json
@@ -3,7 +3,9 @@
   "version": "5.0.0",
   "description": "Conventional changelog plugin for release-it",
   "type": "module",
-  "exports": "./index.js",
+  "exports": {
+    ".": "./index.js",
+    "./package.json": "./package.json"},
   "scripts": {
     "test": "bron test.js --serial",
     "release": "release-it"
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

If you agree with theses changes, I will make a PR

**Comment by webpro** [comment]
This is in [v5.1.0](https://github.com/release-it/conventional-changelog/releases/tag/5.1.0)
