### ISSUE TITLE
Chagelog format conflicts with Prettier

### ISSUE THREAD

**Issue by nbouvrette** [release-it/conventional-changelog#56]
I'm having issues where `conventional-changelog` adds extra space in the markdown file and when I run a build command before a release, Prettier modifies this file and I end up being unable to do the release:

```ts
✔ npm run build
ERROR Working dir must be clean.
Please stage and commit your changes.
Documentation: https://git.io/release-it-git
```

I was thinking of adding the following hook in `release-it.json` to fix it but I don't know if this is the best solution?

```json
{
  "hooks": {
    "after:conventional-changelog:bump": ["npx prettier --write ./CHANGELOG.md"]
  }
}
```

I'm not even sure the syntax is correct?

**Comment by webpro** [comment]
You may need the `git.requireCleanWorkingDir: false` option so this change can be part of the release commit depending on your situation/configuration.

I understand the confusion about the hook names, but the hooks you mention don't exist. Here some examples of hooks that should work:

* `before:init`
* `before:git:init`
* `before:bump`
* `after:bump`
* `after:@release-it/conventional-changelog:bump`
* `before:@release-it/conventional-changelog:release`

Depending on your situation one should fit in your release flow.

You could use the `--verbose` flag or `NODE_DEBUG=release-it:* release-it [...]` to verify whether the command is actually executed.

**Comment by nbouvrette** [comment]
Thanks @webpro 

I tried both with `--verbose` and the command now runs but: 

- `after:@release-it/conventional-changelog:bump`: looks like it's happening before the plugin writes the changelog? Is this normal? Logs below:

```bash
? Select increment (next version): patch (1.1.11)
$ npx prettier --write ./CHANGELOG.md
CHANGELOG.md 29ms

Changeset:
 M CHANGELOG.md
 M package-lock.json
 M package.json
```

- `before:@release-it/conventional-changelog:release`: It seems to be done after the changelog is committed to git, so basically I am left with a changed file uncommitted after the release. Is this also normal? Logs below:

```bash
? Select increment (next version): patch (1.1.10)

Changeset:
 M CHANGELOG.md
 M package-lock.json
 M package.json

$ npx prettier --write ./CHANGELOG.md
CHANGELOG.md 28ms
```

**Comment by webpro** [comment]
(Looking at https://github.com/release-it/conventional-changelog/blob/master/index.js#L164 and https://github.com/release-it/release-it/blob/master/lib/plugin/git/Git.js#L84,) either of these should work:

- `after:@release-it/conventional-changelog:beforeRelease`
- `before:git:beforeRelease`

What can I say, it's a bit of fiddling to get it right sometimes. Totally my bad, it should be documented much better. Now you basically have to read the source code to try to understand it.

**Comment by nbouvrette** [comment]
Wonderful, `after:@release-it/conventional-changelog:beforeRelease` did the trick.

I tried to follow the documentation (not the source code hehe) as best as I could but having some sort of examples could help for sure. I think this one could be a good common case to document as many people use Prettier.

Thanks for your help!
