### ISSUE TITLE
The recommended bump is "undefined"

### ISSUE THREAD

**Issue by domoritz** [release-it/conventional-changelog#59]
I am trying to use this plugin but somehow get a `The recommended bump is "undefined"`. 

```
$ npm run release patch

> vega-embed@6.21.1 release
> release-it patch

WARNING Environment variable "GITHUB_TOKEN" is required for automated GitHub Releases.
WARNING Falling back to web-based GitHub Release.
WARNING The recommended bump is "undefined", but is overridden with "patch".

🚀 Let's release vega-embed (6.21.1...6.21.2)


Changelog:
## <small>6.21.2 (2023-02-13)</small>
* fix: upgrade deps including themes and tooltips, fixes version issues ([ba8ba18](https://github.com/vega/vega-embed/commit/ba8ba18))
```

Shouldn't the fix trigger a patch release?

**Comment by webpro** [comment]
What is the configuration? Maybe the `preset` does not match your commit message convention.

In any case, the idea is that this plugin provides the recommended bump so you should not override with `patch`

**Comment by domoritz** [comment]
Here is my config: https://github.com/vega/vega-embed/blob/main/.release-it.json

**Comment by domoritz** [comment]
Ahh, I need a preset. That wasn't clear to me. It works now that I set the angular preset.
