### ISSUE TITLE
Update conventional-changelog Dependency to Support Changelog Section Sort Order

### ISSUE THREAD

**Issue by wesleyboar** [release-it/conventional-changelog#65]
### Goal

Support sorting / ordering changelog sections i.e.
> **conventional-changelog-conventionalcommits**: sort groups based on config types ([#702](https://github.com/conventional-changelog/conventional-changelog/issues/702)) ([#1002](https://github.com/conventional-changelog/conventional-changelog/issues/1002)) ([0e59f0c](https://github.com/conventional-changelog/conventional-changelog/commit/0e59f0c884bf104e3a6a14c5669c58755cdef064))
> — [v6.1.0](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v6.1.0)

### Idea

In https://github.com/release-it/conventional-changelog, update dependency https://github.com/conventional-changelog/conventional-changelog ([from 3.1.25](https://github.com/release-it/conventional-changelog/blob/5.1.1/package.json#L38)) to [v4.0.0](https://github.com/conventional-changelog/conventional-changelog/blob/11195f2/packages/conventional-changelog/CHANGELOG.md#400-2023-06-05), so it [will include](https://github.com/conventional-changelog/conventional-changelog/blob/11195f2/packages/conventional-changelog/package.json#L41) `conventional-changelog-conventionalcommits` [v6.1.0](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v6.1.0).

### Possibly Related Issues

- https://github.com/conventional-changelog/conventional-changelog/issues/940

**Comment by wesleyboar** [comment]
Workaround: `package.json` property `overrides` ([source](https://github.com/conventional-changelog/conventional-changelog/issues/940#issuecomment-1264766385)) e.g. to `package.json` add:

```json
  "overrides": {
    "conventional-changelog": "^4.0.0"
  },
```

Worked for me.

**Comment by wesleyboar** [comment]
To avoid the workaround, I tried adding —

```
    "writerOpts": {
        "groupBy": "type"
    }
```

— to `.release-it.json`, but the sorting did not change.

**Comment by webpro** [comment]
I bumped versions and released [v6.0.0](https://github.com/release-it/conventional-changelog/releases/tag/6.0.0) - happy to hear whether that does the job?

**Comment by wesleyboar** [comment]
Unfortunately, I paused usage of `release-it` in favor of trying GitHub Actions. It also is not going smoothly.[^1] When I revisit `release-it` solution, I will re-test this.

[^1]: I've begun to believe I am the problem 😅.

**Comment by wesleyboar** [comment]
Thanks for the quick reply and action.
