### ISSUE TITLE
Update peer deps to `release-it` v16

### ISSUE THREAD

**Issue by ghiscoding** [release-it/conventional-changelog#66]
Even though release-it was released as v16, the conventional package still refers to v15 as peer deps, I think it should be updated. The main reason I'm asking is because of the latest security advisory shown by Dependabot, I'm not sure the `normalize-package-data` can be updated but still updating release-it to v16 in a step forward. Thanks

```sh
@release-it/conventional-changelog@6.0.0 requires semver@2 || 3 || 4 || 5 via a transitive dependency on normalize-package-data@2.5.0
@release-it/conventional-changelog@6.0.0 requires semver@^6.3.0 via a transitive dependency on conventional-changelog-writer@6.0.0
@release-it/conventional-changelog@6.0.0 requires semver@^6.3.0 via a transitive dependency on git-semver-tags@5.0.0
@release-it/conventional-changelog@6.0.0 requires semver@7.5.1
```

**Comment by webpro** [comment]
Totally, just _bumped_ into this myself to with the bumper plugin. Just released a new major. Thanks!
