### ISSUE TITLE
semver version should be bumped to fix CVE

### ISSUE THREAD

**Issue by ghiscoding** [release-it/conventional-changelog#67]
I saw that `semver` is using a fixed version in the `package.json`, I think that was maybe a typo that stayed in the code for a long time. It should probably be using the caret prefix as `^7.5.3`, see

https://github.com/release-it/conventional-changelog/blob/7c90551bf556c479e1a40b79609b1f500fb8bee6/package.json#L40

and this would partially fix the following CVE issue

> @release-it/conventional-changelog@7.0.0 requires semver@7.5.1

> Versions of the package semver before 7.5.2 on the 7.x branch, before 6.3.1 on the 6.x branch, and all other versions before 5.7.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.

Please note that this **will not fix** all `semver` issues since `conventional-changelog-core` is pointing to an old `semver` version via a transitive dependency of `read-pkg@3.0.0` as I pointed out in this conventional-changelog issue [comment](https://github.com/conventional-changelog/conventional-changelog/issues/1019#issuecomment-1644110023). It's probably going to take a long while since maintenance on that project are moving at a rather slow pace.

Until conventional-changelog team release a fix, I use a simple yarn resolution in the meantime
```js
"resolutions": {
    "semver": "^7.5.4"
},
```

**Comment by nbouvrette** [comment]
Since this is coming back week after week I'm adding back the issues where this is being working on: https://github.com/conventional-changelog/conventional-changelog/issues/1019

**Comment by ghiscoding** [comment]
It was fixed over the weekend, via this `conventional-changelog` [PR](https://github.com/conventional-changelog/conventional-changelog/pull/1071), but yet to be released

**Comment by nbouvrette** [comment]
Looks like they didn't release a new version yet... I asked for a follow up so we can hopefully close this soon

**Comment by nbouvrette** [comment]
@ghiscoding I think the `conventional-changelog` fix is finally out - I open [another issue](https://github.com/release-it/release-it/issues/1037) here so get extra visibility on releasing a fix here.

**Comment by webpro** [comment]
Should be fixed in v7.0.1, so closing this one.
