### ISSUE TITLE
Problem with changelog generation and version bumping

### ISSUE THREAD

**Issue by b12k** [release-it/conventional-changelog#7]
Hello.
I'm facing some problems with release Changelog generation and sometime version bumping.
I'm using release-it in multiple projects and have some problems, which I think are related to conventional-changelog plug-in.

### Problem #1: 
Every time we do a release - commits from all previous releases are mentioned in new release.
It affects version bumping.
```
v0.3.0 => expected 0.1.2
  fix: some fix 2
  fix: some fix 1
  feat: some feature 1
v0.2.0 => expected 0.1.0
  fix: some fix 1
  feat: some feature 1
v0.1.0
  feat: some feature 1
```

### Problem #2:
Example repo: [https://github.com/b12k/release-test](https://github.com/b12k/release-test)

Changelog is badly generated (Sorry for bad description ^_^ ). You can compare change log of example repo with releases.

Release-it is configured the same way in both projects with 
```
"preset": "conventionalcommits"
```

I assume the problem is not in the `conventional-changelog` or `conventional-recommended-bump` but either with this plug-in or my hands =)

Thanx in advance!

**Comment by webpro** [comment]
Thanks for raising the issue. I've just released [v1.1.3](https://github.com/release-it/conventional-changelog/releases/tag/1.1.3) that should fix things and be more stable.
