### ISSUE TITLE
releaseCount not work

### ISSUE THREAD

**Issue by little-buddy** [release-it/conventional-changelog#73]
When I run 
```
npx conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 0
```
It's fine.

use @release-it
```
plugins: {
    '@release-it/conventional-changelog': {
      preset: {
        name: 'conventionalcommits',
        types,
        preMajor: false,
        gitRawCommits: {
          context: {
            format:
              '%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n-authorName-%n%an%n-authorEmail-%n%ae',
          },
        },
      },
      infile: 'CHANGELOG.md',
      header: '# Changelog',
      ignoreRecommendedBump: false,
      releaseCount: 0,
    },
}
```

the releaseCount not work.

`environment`
node@16.20.2
@release-it/conventional-changelog@5.1.1
release-it@15.11.0

**Comment by little-buddy** [comment]
I find `conventional-changelog-cli@4.0.0` run with `conventional-changelog-core@6.0.0`
but `@release-it@15.11.0` run with `conventional-changelog-core@4.2.4`

<img width="400" alt="image" src="https://github.com/release-it/conventional-changelog/assets/30054881/90abd929-d350-4957-a841-d4cede0ce84e">



<img width="420" alt="image" src="https://github.com/release-it/conventional-changelog/assets/30054881/9b211409-9896-4a8b-8b10-ca5cf3bc2d6a">

**Comment by little-buddy** [comment]
I test  @release-it/conventional-changelog@3.3.0, it workd fine, Except the changlog is in reverse order
I think the corresponding adaptation version should be marked, 
otherwise it will not always be possible in the latest environment 😭

**Comment by little-buddy** [comment]
After I synchronized their dependent versions and upgraded the release-it to the latest, and read the code for the esModule version, I found that it was my personal unfamiliarity that caused the problem
So Sorry~

**Comment by webpro** [comment]
No worries, @little-buddy. Glad you sorted it out. Let me know if there's something I could improve e.g. in the documentation.
