### ISSUE TITLE
issues with changelog modifcation behavior

### ISSUE THREAD

**Issue by abmusse** [release-it/conventional-changelog#76]
I'm currently using release-it with conventional commits with following config:

https://github.com/IBM/nodejs-itoolkit/blob/cea61549fc197f9267af00befa06fa76df67c18c/.release-it.json#L1

I'm cutting a new release and noticed the change log is barren and missing a bunch of commits with:

- build:
- ci:

See commits that should be included here: 

https://github.com/IBM/nodejs-itoolkit/compare/v1.0.1...master

I'm running the following release-it command:

https://github.com/IBM/nodejs-itoolkit/blob/cea61549fc197f9267af00befa06fa76df67c18c/package.json#L16

So far my CHANGELOG.md has been modified with:

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 2587999..a75884d 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,3 +1,7 @@
+
+
+## [1.0.2](https://github.com/IBM/nodejs-itoolkit/compare/v1.0.1...v1.0.2) (2023-10-10)
+
 # Changelog
 
 ## [1.0.1](https://github.com/IBM/nodejs-itoolkit/compare/v1.0.0...v1.0.1) (2022-10-31)
@@ -225,4 +229,4 @@
 
 ### [0.1.5](https://github.com/IBM/nodejs-itoolkit/compare/0.1.4...0.1.5) (2019-01-08)
 
-### 0.1.4 (2018-09-17)
+### 0.1.4 (2018-09-17)
\ No newline at end of file
```
There a few issues with the change log

1) It adds the new release 1.0.2 at the top of the file before the `# Changelog` header.
2) The [commits](https://github.com/IBM/nodejs-itoolkit/compare/v1.0.1...master) are not added under the 1.0.2 header
3) It also removes the newline at the end of the file.

I would expect the above to not be issues.
Any tips on getting these resolved?

**Comment by webpro** [comment]
Are you using the latest version of everything? At least do `"preset": "conventionalcommits"` → `"preset": { "name": "conventionalcommits"`}`

**Comment by fwextensions** [comment]
FWIW, I had a similar problem with the changelog title getting repeated, even though I had the header value set.  I was using `"header": "# Changelog\n\n"`, to try to control the spacing after the title.  That didn't seem to have any effect on the spacing *and* duplicated the header.  Removing the `\n\n` got it working.

I also wish it didn't strip the last newline in the file.

**Comment by webpro** [comment]
Sorry for the delay @abmusse, somehow I missed it. Added the `EOL` in v8.0.1 :)
