### ISSUE TITLE
the link of compare tags is wrong

### ISSUE THREAD

**Issue by YOEL311** [release-it/conventional-changelog#82]
I try to release with the ``release-it`` package with your fantastic plugin

````
 git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/testChangeLog

🚀 Let's release ****/theme (1.2.5...1.2.6)


Changelog:
## [1.2.6](https://******/compare/v1.2.4...v1.2.6) (2024-02-06)

### Bug Fixes
````

but the link to compare tags is  not correct

``## [1.2.6](https://******/compare/v1.2.4...v1.2.6) (2024-02-06)``

this need to be link to compare

``https://**repolink**/branchcompare/?baseVersion=GTv1.2.2&targetVersion=GTv1.2.6``

my relevate ``package.json``

````
"@release-it/conventional-changelog": "8.0.1",
"@release-it/keep-a-changelog": "5.0.0",
"release-it": "^17.0.1",



  "plugins": {
      "@release-it/conventional-changelog": {
        "infile": "CHANGELOG.md",
        "preset": "angular",
        "context": {
          "commit": "commit"
        }
      },
      "@release-it/keep-a-changelog": {
        "addUnreleased": true,
        "keepUnreleased": true,
        "filename": "CHANGELOG.md",
        "head": "main",
        "addVersionUrl": true,
        "versionUrlFormats": {
          "repositoryUrl": "*****",
          "unreleasedUrl": "*****/branchCompare?baseVersion=GT{tagName}&targetVersion=GB{head}",
          "versionUrl": "****/branchCompare?baseVersion=GT{previousTag}&targetVersion=GT{tagName}",
          "firstVersionUrl": "***?version=GT{tagName}"
        }
      }
    }

````

**Comment by webpro** [comment]
Hi @YOEL311, feel free to open a PR with a fix.

**Comment by YOEL311** [comment]
@webpro 
@matthiasritter
I solve that with the specific configuration of my compare link
this link ``https://******/compare/v1.2.4...v1.2.6)``works with GitHub but not all services of Git support that

example compare links that work with GitHub
https://github.com/facebook/react-native/compare/v0.72.0...v0.73.0


````
 "plugins": {
      "@release-it/conventional-changelog": {
        "infile": "CHANGELOG.md",
        "preset": {
          "name": "conventionalcommits",
          "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/branchCompare?baseVersion=GT{{previousTag}}&targetVersion=GT{{currentTag}}"
        },
      }
    }
````


you can see here all config option

https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

**Comment by webpro** [comment]
Thanks @YOEL311! That's useful for other users as well.
