### ISSUE TITLE
generate new CHANGELOG.md file for previous changelogs

### ISSUE THREAD

**Issue by Motphys** [release-it/conventional-changelog#85]
I've a project contains no `CHANGELOG.md` file but some existing tags (e.g. `v1.0.0`).

Now I'm trying to use `release-it` and I'd like to generate a `CHANGELOG.md` file with all changelogs of previous versions. But what I got is only the changelogs since last version.

I've tried [`conventional-changelog-cli`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli#quick-start):

```bash
$ conventional-changelog -p angular -i CHANGELOG.md -s -r 0
```

This command gives me changelogs of all versions, however I'd like to be able to use the configuration of `release-it`.

**Comment by jarodsmk** [comment]
@Motphys are you thinking of clearing all the pre-release changelogs and aggregating those changes under the new production release?

Seems that's not possible according to this [thread](https://github.com/release-it/conventional-changelog/issues/62)

**Comment by Motphys** [comment]
> @Motphys are you thinking of clearing all the pre-release changelogs and aggregating those changes under the new production release?
> 
> Seems that's not possible according to this [thread](https://github.com/release-it/conventional-changelog/issues/62)


No, I was trying to generate changelog for an old project that has never generated changelog file.

Anyway I got it done with [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli#quick-start), with proper command line arguments.

Thanks.
