### ISSUE TITLE
Upgrade conventional-recommended-bump and conventional-changelog

### ISSUE THREAD

**Issue by will-stone** [release-it/conventional-changelog#88]
Both [conventional-recommended-bump](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-recommended-bump/CHANGELOG.md) and [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog/CHANGELOG.md) have had new releases. 

[I've attempted](https://github.com/release-it/conventional-changelog/compare/master...will-stone:release-it-conventional-changelog:main?expand=1) to upgrade these using the new Bumper class, but I get the following error:

```
TypeError: yield* (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value) is not async iterable
```

Would you like me to submit the broken PR as a starter? Not that I've done much, but I'm hoping you'll be able to spot the required changes, being more familiar with the code and packages.

Thanks 😄

**Comment by webpro** [comment]
Yeah I've briefly looked at the updates and they're significantly breaking. Feel free to take a stab it, happy to review a PR!

**Comment by will-stone** [comment]
Thanks for the recent update, I still need to see what I need to do with [my plugin](https://github.com/commits-with-character/conventional-changelog-preset) to make it compatible but that's my problem, let's close this 😎

**Comment by webpro** [comment]
Thanks for pushing it, though!
