### ISSUE TITLE
v1.1.1 is a BREAKING change from v1.1.0

### ISSUE THREAD

**Issue by tim-lai** [release-it/conventional-changelog#9]
Hello,

We currently used `release-it@12.4.3` and `@release-it/conventional-changelog@1.1.0`. We release against Node 8.11.4. We also test against Node v10.5.

`release-it@12.6.3` and `@release-it/conventional-changelog@1.1.4` are both BREAKING CHANGES in our release process (Node 8).

`@release-it/conventional-changelog@1.1.4` requires `release-it@13.5.3`, which itself requires Node v10.6 or greater. Therefore, the stated requirement Node > 10 is not accurate.

Fyi, one of the breaking Release-it dependencies is `cacheable-lookup`, which requires a method introduced in Node v10.6.

`@release-it/conventional-changelog@1.1.1` requires `release-it@13`, which dropped Node 8 support.

**Comment by webpro** [comment]
Sorry for any inconvenience, I didn't realize this at the time. I'll do better next time.
